apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: haproxy

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - network-policy.yaml
  - servicemonitor.yaml

commonLabels:
  app.kubernetes.io/name: haproxy
  app.kubernetes.io/component: load-balancer
  app.kubernetes.io/part-of: planet-proxy
  app.kubernetes.io/managed-by: kustomize
  environment: production
