apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-production.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - hpa.yaml

labels:
  - pairs:
      app.kubernetes.io/name: planet-proxy
      app.kubernetes.io/managed-by: kustomize
