apiVersion: v1
kind: Service
metadata:
  name: planet-proxy-service
  labels:
    app: planet-proxy
    component: api
spec:
  type: ClusterIP
  selector:
    app: planet-proxy
    component: api
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
